export const SET_LOADING = 'SET_LOADING';
export const SEARCH_WEATHER = 'SEARCH_WEATHER';
export const SEARCH_LOCATIONS = 'SEARCH_LOCATIONS';
export const SEARCH_CITIES = 'SEARCH_CITIES';
export const SEARCH_STATEPROVINCES = 'SEARCH_STATEPROVINCES';
export const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES';